/*
-------------------------------------------------------------------------
sphere.c
-------------------------------------------------------------------------
This program will generate a given number of points uniformly distributed
on the surface of a sphere. The number of points is given on the command
line as the first parameter.  Thus `sphere 100' will generate 100 points 
on the surface of a sphere, and output them to stdout.
	A number of different command-line flags are provided to set the 
radius of the sphere, control the output format, or generate points on 
an ellipsoid.  The definition of the flags is printed if the program is 
run without arguments: `sphere'.
	The idea behind the algorithm is that for a sphere of radius r, the 
area of a zone of width h is always 2*pi*r*h, regardless of where the sphere 
is sliced.  The implication is that the z-coordinates of random points on a 
sphere are uniformly distributed, so that x and y can always be generated by 
a given z and a given angle.
	The default output is integers, rounded from the floating point 
computation.  The rounding implies that some points will fall outside
the sphere, and some inside.  If all are required to be inside, then
the calls to irint() should be removed.  
	The flags -a, -b, -c are used to set ellipsoid axis lengths.  
Note that the points are not uniformly distributed on the ellipsoid: they 
are uniformly distributed on the sphere and that is scaled to an ellipsoid.
	random() is used to generate random numbers, seeded with time().
How to compile:
	gcc -o sphere sphere.c -lm

Reference: J. O'Rourke, Computational Geometry Column 31,
Internat. J. Comput. Geom. Appl. 7(4) 379--382 (1997); 
also in SIGACT News, 28(2):20--23 (1997), Issue 103.

Written by Joseph O'Rourke and Min Xu, June 1997.
Used in the textbook, "Computational Geometry in C."
Questions to orourke@cs.smith.edu.
--------------------------------------------------------------------
This code is Copyright 1997 by Joseph O'Rourke.  It may be freely
redistributed in its entirety provided that this copyright notice is
not removed.
--------------------------------------------------------------------
*/

#include "const.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>

//generate points on spheres with a random number generator...
void points_on_sphere(int dustnumber, int numberofpoints)
{
  int n, ct;		/* number of points */
  double x, y, z, w, t;
  double r;		/* true radius */
  double r1, r2, r3;	/* ellipsoid axis lengths */
  init_primeroot(0);	

  r = dradius[dustnumber]; //in number of grid points
  r = r*dx; //all points should be in normalized coordinates (dx is already normalized)
  r1 = r2 = r3 = r; 
  n = numberofpoints; //numberofgenerated points
 ct=0;
  while (n--) {
    /* Generate a random point on a sphere of radius 1. */
    /* the sphere is sliced at z, and a random point at angle t
       generated on the circle of intersection. */
    z = 2.0 * primeroot() -1;
    t = 2.0 * M_PI * primeroot();
    w = sqrt( 1 - z*z );
    x = w * cos( t );
    y = w * sin( t );
    
	dustxdx[dustnumber][ct]=r1*x;
	dustydy[dustnumber][ct]=r2*y;
	dustzdz[dustnumber][ct]=r3*z;
	//dustrho[dustnumber][ct]=0.0;
	ct++;
  }
}
