##
##	PINC Makefile
##	Author: Sigvald Marholm
##	University of Oslo, Norway 
##	2015
##
EXEC	= pinc
CC	= gcc
CFLAGS	= -std=c99

$(EXEC):
	$(CC) $(CFLAGS) main.c -o $(EXEC)

clean:
	rm -f $(EXEC) *.o *~
