/*
 * stool.h - Simple Tool
 *
 * Author: Sigvald Marholm
 * Date: 16.06.15
 */

#ifndef STOOL_H_
#define STOOL_H_

#define _XOPEN_SOURCE 700

#include <stdio.h>
#include <stdlib.h>
// #include <time.h>

#define GETLINESBUFFER 4096		// fgetlines() gets faster for larger buffers
#define GPSCRIPT "gplot.gp"		// Filename for gnuplot-script generated by gplot
#define GPDATA "gplot.data"		// Filename for data generated by gplot

/*
 * TIMING FUNCTIONS (t-functions)
 */

void tprobe(const char * label);


/*
 * VECTOR FUNCTIONS (v-functions)
 */

void vsetall(double *v, int N, double value);
double vmax(double *v, int N);
double vmin(double *v, int N);
double vext(double *v, int N);
double vavg(double *v, int N);
void vadd(double *v, int N, double value);
void vmul(double *v, int N, double value);
void vprint(double *v, int N);
double vdev(double *v, int N, double value);


/*
 * FILE HANDLING FUNCTIONS (f-functions)
 */
/*
unsigned long fgetlines(const char *fname);
*/
/*
 * GRAPHICS FUNCTIONS (g-functions)
 */
/*
void gplot(const double *x, const double *y, int N, const char *legend);
void gdraw();
void gqplot(const double *x, const double *y, int N, const char *title);
FILE* gget();
void gcmd(const char* str);
void gtitle(const char *str);
void gxlabel(const char *str);
void gylabel(const char *str);
void gxrange(double from, double to);
void gyrange(double from, double to);
void ggrid();
void gclose();
*/
#endif /* STOOL_H_ */
